Support %{..} in toolbox <category name="...">
LLK/scratch-blocks pull request #1600
Opened 2018-06-18 20:19 UTC by AnmAtAnm

### Proposed Changes

Allow `%{..}` references in toolbox `<category name="...">`.

Still requires #1599 to render the generated section `<label>`.

### Reason for Changes

Support toolbox localization and runtime locale changes.

### Test Coverage

Tested in `vertical_playground.html`.

2018-06-18 21:25 UTC, chrisgarrity requested changes
It all makes sense. There's just a couple of changes needed to reduce the work (and potential confusion) for translators.

2018-06-18 21:25 UTC, chrisgarrity commented on msg/messages.js
> +Blockly.Msg.CATEGORY_VARIABLES = 'Data';
This is the label that translators are currently translating, and in Scratch 3.0 it should be 'Variables', so we shouldn't change this value.

2018-06-18 21:25 UTC, chrisgarrity commented on blocks_vertical/default_toolbox.js
> +  '<category name="%{BKY_CATEGORY_EXTENSIONS}" id="extensions" colour="#FF6680" secondaryColour="#FF4D6A" '+
I think we should just leave Extensions untranslated for now. It's not in scratch-gui (extensions provide their own name), and I'm trying not to give translators anything that they can't see in the gui. It leads to many questions.

2018-06-18 21:25 UTC, chrisgarrity commented on core/toolbox.js
> +      Blockly.utils.replaceMessageReferences(this.name_));
Looks good!

2018-06-18 21:25 UTC, chrisgarrity commented on msg/messages.js
> +Blockly.Msg.CATEGORY_EXTENSIONS = 'Extensions';
Remove this line - leaving 'extensions' untranslated above.

2018-06-19 17:17 UTC, AnmAtAnm reviewed
Made requested changes.

2018-06-19 17:17 UTC, AnmAtAnm commented on blocks_vertical/default_toolbox.js
> +  '<category name="%{BKY_CATEGORY_EXTENSIONS}" id="extensions" colour="#FF6680" secondaryColour="#FF4D6A" '+
Understood. Done.

Do we need a comment to clarify for future devs?

2018-06-19 17:17 UTC, AnmAtAnm commented on msg/messages.js
> +Blockly.Msg.CATEGORY_VARIABLES = 'Data';
Reverted here and in `scratch_mgs.js`.

2018-06-19 17:17 UTC, AnmAtAnm commented on msg/messages.js
> +Blockly.Msg.CATEGORY_EXTENSIONS = 'Extensions';
Reverted here and in `scratch_mgs.js`.

2018-06-20 12:49 UTC, chrisgarrity approved these changes
Thanks @AnmAtAnm

2018-06-20 12:50 UTC, merged