Fix extra events being emitted from the color slider
LLK/scratch-blocks pull request #1815
Opened 2018-12-10 22:17 UTC by paulkaplan

### Resolves

_What Github issue does this resolve (please include link)?_

Related to LLK/scratch-vm#1695, we were getting echo events from setting the initial slider values. 

Move the call to set those values above the callbacks being bound to avoid this.

2018-12-10 22:50 UTC, kchadha requested changes
Hmmm for some reason this change makes it so that the slider thumbs are not initialized to the correct positions when the field editor is opened...

2018-12-11 19:28 UTC, paulkaplan commented
Fixed, thanks for catching that.

2018-12-11 19:54 UTC, kchadha approved these changes
LGTM

2018-12-11 22:12 UTC, kchadha commented
Merging since I need these changes for the PR I am about to submit.

2018-12-11 22:17 UTC, merged