Make event filtering stricter for move events (blockly#1892)
LLK/scratch-blocks pull request #2068
Opened 2020-05-13 17:31 UTC by adroitwhiz

Well, this was a fun way to spend 3 hours!

### Resolves

Resolves https://github.com/LLK/scratch-gui/issues/4400

### Proposed Changes

This PR brings over the event merging changes from https://github.com/google/blockly/pull/1892/.

### Reason for Changes

Changing the sprite menu in the "(attribute) of (sprite)" block triggers a workspace update, which rebuilds the entire Blockly workspace.

When rebuilding a workspace, blocks are first created with their position at the origin and then moved to their proper positions. The VM should be able to track that via events emitted from Blockly, e.g.:
- Block A is created at position (0, 0).
- Block A is moved to position (500, 100).

However, in certain cases (e.g. when you change the menu in the toolbox/flyout, maybe other cases?), these events are emitted twice:
- Block A is created at position (0, 0).
- Block A is moved to position (500, 100).
- Block A is created at position (0, 0).
- Block A is moved to position (500, 100).

The previous event merging behavior would incorrectly merge the second move event into the first, as such:
- Block A is created at position (0, 0).
- Block A is moved to position (500, 100).
- Block A is created at position (0, 0).

This would cause the VM to think that Block A should remain at (0, 0). This would be repeated for every top-level block in the current sprite's workspace, causing them all to be reset to (0, 0).

### Test Coverage

Tests were ported from Blockly

2020-05-13 18:22 UTC, adroitwhiz commented
@rachel-fenichel Sorry about the lack of attribution on https://github.com/LLK/scratch-blocks/pull/2068/commits/fccb5e11d33b0a823a4964870e65ae3e12092d9b! Fixed it now

2020-05-13 18:23 UTC, rachel-fenichel commented
Oh I'm not worried about attribution! Just sad that it took lots of digging to find a previously solved problem.

2020-06-02 20:18 UTC, cwillisf commented
@picklesrus any chance you have time to review this? I feel like I'm in over my head in terms of scratch-blocks. In talking with @adroitwhiz (and referring to 6275e1137c9be43ff8a94dcf8139196cb384e657) it does look like adding `wouldConnectBlock` to both `DraggedConnectionManager` and `InsertionMarkerManager` makes sense.

2020-06-02 20:43 UTC, fsih commented on core/insertion_marker_manager.js
> +Blockly.InsertionMarkerManager.prototype.wouldConnectBlock = function() {
Why do we need this function?

2020-06-02 20:45 UTC, fsih approved these changes
LGTM! Since it's bringing in an upstream change I think it should be safe, but would feel better if @picklesrus, @kchadha or @paulkaplan sanity-checked

2020-06-02 20:53 UTC, rachel-fenichel commented
As I recall, scratch-blocks doesn't use the dragged connection manager and so it doesn't matter if you add the code in there or not.

The dragged connection manager handled blockly-style yellow highlights. The insertion marker manager handles insertion markers. They share an API and for a while both files existed next to each other, but I don't think you're ever instantiating a dragged connection manager. And there's no inheritance going on either.

2020-06-09 13:42 UTC, picklesrus commented
What Rachel said :) Scratch blocks instantiates InsertionmarkerManager in block dragger, not DraggedConnectionManager so that code shouldn't matter.  Looks like we're setting closestConnection_ in the same way that Blockly does too so I'm pretty sure this is fine for the blocks. During testing we should verify that insertion markers continue to work as we expect. 

To me, knowing whether the VM is somehow depending on the event that was merged is trickier to verify. @adroitwhiz would you work with folks to make a test plan for this? Happy to help!  In addition to testing that the bug with that sensing block is fixed and insertion markers still work as expected, here are some random initial thoughts on things that may generate events: switching sprites, switching between code/sound/paint tabs, switching to the stage & back to a sprite, editor->project page->editor, share the love, changing values in the sprite pane, moving blocks around, undo/redo, clean up blocks, deleting blocks in a way that resizes the workspace, load project from a file.   I think considering something like this list while the project is running is important too. Maybe @cwillisf has thoughts on whether I should be concerned about how these things interact with the VM or not?

2020-06-09 14:28 UTC, fsih commented
Thanks Katelyn for helping us ideate about a test plan!

2020-06-12 10:57 UTC, picklesrus requested changes
Whoops! Sorry! Previous comment (deleted now) was meant for a different PR. Ignore me -- I have too many tabs open :)

2020-07-09 18:33 UTC, merged