Zoom controls
LLK/scratch-blocks pull request #808
Opened 2017-02-21 21:49 UTC by thisandagain

### Resolves

GH-43

### Proposed Changes

- Makes trashcan hidden by default
- Updates zoom controls as per #43 and discussion with @carljbowman 
- Replaces use of `sprites.png` with individual SVG assets for each zoom control (easier to maintain)

2017-02-21 22:18 UTC, thisandagain commented
Note to self: squash during merge

2017-02-22 00:18 UTC, rschamp requested changes
Just one syntax thing — tested it out in the GUI and the VM, looks/works great!

2017-02-22 00:18 UTC, rschamp commented on core/zoom_controls.js
> +Blockly.ZoomControls.prototype.ZOOM_RESET_PATH = 'zoom-reset.svg';
Nit on these, private vars conventionally end in `_`

2017-02-22 02:23 UTC, thisandagain commented
@rschamp Good catch. Fixed.

2017-02-22 15:54 UTC, rschamp approved these changes

2017-02-22 16:33 UTC, merged