New dragging!  Merge from master
LLK/scratch-blocks pull request #891
Opened 2017-05-17 01:02 UTC by rachel-fenichel

This change picks up all of my new dragging code, plus some of the new variable code.

It's ginormous but I've checked it against https://github.com/google/blockly/pull/1078 and I'm pretty happy with it.

All of the insertion marker code now lives in insertion_marker_manager.js, which has the same API as dragged_connection_manager.js.  This should help reduce conflicts between scratch and blockly codebases.

2017-05-17 01:03 UTC, rachel-fenichel commented
One conflict in flyout_vertical, related to checkboxes, which I will check out tomorrow.

2017-05-17 18:31 UTC, fsih commented
Fixes https://github.com/LLK/scratch-blocks/issues/893

2017-05-18 12:10 UTC, paulkaplan commented
@rachel-fenichel thanks for walking me through this, sorry about the delay. 

Pulling and building to use for `scratch-gui` I get this error:
![image](https://cloud.githubusercontent.com/assets/654102/26201542/7fa381d6-3ba1-11e7-8632-f1ea5cc38473.png)

2017-05-18 12:47 UTC, paulkaplan commented
@rachel-fenichel It looks like something changed the behavior of the delete cursor style. Here is what it used to do:

![delete-cursor](https://cloud.githubusercontent.com/assets/654102/26202741/8426b7d2-3ba6-11e7-9669-9c3cc8f8c434.gif)

And now there is no "x" cursor style:
![no-delete-cursor](https://cloud.githubusercontent.com/assets/654102/26202736/81c8c9ee-3ba6-11e7-9154-ceb676477a1c.gif)

2017-05-18 14:29 UTC, paulkaplan requested changes
Left feedback as other comments. Looks like a couple minor things and one (possibly) bigger problem.

2017-05-18 14:29 UTC, paulkaplan commented on core/workspace.js
>    this.variableList.length = 0;
Looks like this `this.variableList.length = 0` was missed, I think it should be removed (line 205 of new code).

2017-05-18 21:44 UTC, rachel-fenichel commented
Fixed all three.  Thanks for the details on the deletion one.  They made it easy to fix.

2017-05-18 23:41 UTC, rachel-fenichel commented
Oh wait--now if I have an insertion marker and transition to needing a deletion hand, the insertion marker remains.  That's no good.

2017-05-19 00:11 UTC, rachel-fenichel commented
Okay, I've fixed that one as well.

2017-05-19 14:57 UTC, paulkaplan commented
Great thanks @rachel-fenichel! Looks good to me now.

2017-05-19 16:03 UTC, paulkaplan commented
Wait sorry getting a similar require error for `Uncaught TypeError: Blockly.VariableModel is not a constructor` from `VariableMap.createVariable`.

2017-05-19 23:00 UTC, rachel-fenichel commented
Fixed missing require.

2017-05-22 20:06 UTC, rachel-fenichel commented
Verbally okayed by Paul.

2017-05-22 20:08 UTC, merged